<?xml version="1.0" encoding="US-ASCII" standalone="yes"?>
<!DOCTYPE dta [
<!ELEMENT dta (header, descriptors,
variable_labels, expansion,
data, value_labels)>
<!ELEMENT header (ds_format, byteorder,
filetype, nvar, nobs, data_label,
time_stamp)>
<!ELEMENT ds_format (#PCDATA)>
<!ELEMENT byteorder (#PCDATA)>
<!ELEMENT filetype (#PCDATA)>
<!ELEMENT nvar (#PCDATA)>
<!ELEMENT nobs (#PCDATA)>
<!ELEMENT data_label (#PCDATA)>
<!ELEMENT time_stamp (#PCDATA)>
<!ELEMENT descriptors (typelist, varlist,
srtlist, fmtlist, lbllist)>
<!ELEMENT typelist (type)+>
<!ELEMENT type (#PCDATA)>
<!ATTLIST type varname IDREF #REQUIRED>
<!ELEMENT varlist (variable)+>
<!ELEMENT variable EMPTY>
<!ATTLIST variable varname ID #REQUIRED>
<!ELEMENT srtlist (sort)*>
<!ELEMENT sort EMPTY>
<!ATTLIST sort varname IDREF #REQUIRED>
<!ELEMENT fmtlist (fmt)+>
<!ELEMENT fmt (#PCDATA)>
<!ATTLIST fmt varname IDREF #REQUIRED>
<!ELEMENT lbllist (lblname)*>
<!ELEMENT lblname (#PCDATA)>
<!ATTLIST lblname varname IDREF #REQUIRED>
<!ELEMENT variable_labels (vlabel)*>
<!ELEMENT vlabel (#PCDATA)>
<!ATTLIST vlabel varname IDREF #REQUIRED>
<!ELEMENT expansion (char)*>
<!ELEMENT char (#PCDATA)>
<!ATTLIST char name  NMTOKEN #REQUIRED>
<!ATTLIST char vname NMTOKEN #REQUIRED>
<!ELEMENT data (o)*>
<!ELEMENT o (v)*>
<!ATTLIST o num NMTOKEN #IMPLIED>
<!ELEMENT v (#PCDATA)*>
<!ATTLIST v varname IDREF #IMPLIED>
<!ELEMENT value_labels (vallab)*>
<!ELEMENT vallab (label)+>
<!ATTLIST vallab name  NMTOKEN #REQUIRED>
<!ELEMENT label (#PCDATA)>
<!ATTLIST label value NMTOKEN #REQUIRED>
]>
<dta>
<header>
<ds_format>113</ds_format>
<byteorder>LOHI</byteorder>
<filetype>1</filetype>
<nvar>5</nvar>
<nobs>28</nobs>
<data_label></data_label>
<time_stamp>7 Dec 2009 16:06</time_stamp>
</header>
<descriptors>
<typelist>
<type varname='mi_byte'>byte</type>
<type varname='mi_int'>int</type>
<type varname='mi_long'>long</type>
<type varname='mi_float'>float</type>
<type varname='mi_double'>double</type>
</typelist>
<varlist>
<variable varname='mi_byte'/>
<variable varname='mi_int'/>
<variable varname='mi_long'/>
<variable varname='mi_float'/>
<variable varname='mi_double'/>
</varlist>
<srtlist>
<sort varname='mi_int'/>
</srtlist>
<fmtlist>
<fmt varname='mi_byte'>%8.0g</fmt>
<fmt varname='mi_int'>%8.0g</fmt>
<fmt varname='mi_long'>%12.0g</fmt>
<fmt varname='mi_float'>%9.0g</fmt>
<fmt varname='mi_double'>%10.0g</fmt>
</fmtlist>
<lbllist>
<lblname varname='mi_byte'></lblname>
<lblname varname='mi_int'></lblname>
<lblname varname='mi_long'></lblname>
<lblname varname='mi_float'></lblname>
<lblname varname='mi_double'></lblname>
</lbllist>
</descriptors>
<variable_labels>
<vlabel varname='mi_byte'></vlabel>
<vlabel varname='mi_int'></vlabel>
<vlabel varname='mi_long'></vlabel>
<vlabel varname='mi_float'></vlabel>
<vlabel varname='mi_double'></vlabel>
</variable_labels>
<expansion>
</expansion>
<data>
<o>
<v>0</v>
<v>0</v>
<v>0</v>
<v>0.000000000000000</v>
<v>0.0000000000000000000000000</v>
</o>
<o>
<v>.</v>
<v>.</v>
<v>.</v>
<v>.</v>
<v>.</v>
</o>
<o>
<v>.a</v>
<v>.a</v>
<v>.a</v>
<v>.a</v>
<v>.a</v>
</o>
<o>
<v>.b</v>
<v>.b</v>
<v>.b</v>
<v>.b</v>
<v>.b</v>
</o>
<o>
<v>.c</v>
<v>.c</v>
<v>.c</v>
<v>.c</v>
<v>.c</v>
</o>
<o>
<v>.d</v>
<v>.d</v>
<v>.d</v>
<v>.d</v>
<v>.d</v>
</o>
<o>
<v>.e</v>
<v>.e</v>
<v>.e</v>
<v>.e</v>
<v>.e</v>
</o>
<o>
<v>.f</v>
<v>.f</v>
<v>.f</v>
<v>.f</v>
<v>.f</v>
</o>
<o>
<v>.g</v>
<v>.g</v>
<v>.g</v>
<v>.g</v>
<v>.g</v>
</o>
<o>
<v>.h</v>
<v>.h</v>
<v>.h</v>
<v>.h</v>
<v>.h</v>
</o>
<o>
<v>.i</v>
<v>.i</v>
<v>.i</v>
<v>.i</v>
<v>.i</v>
</o>
<o>
<v>.j</v>
<v>.j</v>
<v>.j</v>
<v>.j</v>
<v>.j</v>
</o>
<o>
<v>.k</v>
<v>.k</v>
<v>.k</v>
<v>.k</v>
<v>.k</v>
</o>
<o>
<v>.l</v>
<v>.l</v>
<v>.l</v>
<v>.l</v>
<v>.l</v>
</o>
<o>
<v>.m</v>
<v>.m</v>
<v>.m</v>
<v>.m</v>
<v>.m</v>
</o>
<o>
<v>.n</v>
<v>.n</v>
<v>.n</v>
<v>.n</v>
<v>.n</v>
</o>
<o>
<v>.o</v>
<v>.o</v>
<v>.o</v>
<v>.o</v>
<v>.o</v>
</o>
<o>
<v>.p</v>
<v>.p</v>
<v>.p</v>
<v>.p</v>
<v>.p</v>
</o>
<o>
<v>.q</v>
<v>.q</v>
<v>.q</v>
<v>.q</v>
<v>.q</v>
</o>
<o>
<v>.r</v>
<v>.r</v>
<v>.r</v>
<v>.r</v>
<v>.r</v>
</o>
<o>
<v>.s</v>
<v>.s</v>
<v>.s</v>
<v>.s</v>
<v>.s</v>
</o>
<o>
<v>.t</v>
<v>.t</v>
<v>.t</v>
<v>.t</v>
<v>.t</v>
</o>
<o>
<v>.u</v>
<v>.u</v>
<v>.u</v>
<v>.u</v>
<v>.u</v>
</o>
<o>
<v>.v</v>
<v>.v</v>
<v>.v</v>
<v>.v</v>
<v>.v</v>
</o>
<o>
<v>.w</v>
<v>.w</v>
<v>.w</v>
<v>.w</v>
<v>.w</v>
</o>
<o>
<v>.x</v>
<v>.x</v>
<v>.x</v>
<v>.x</v>
<v>.x</v>
</o>
<o>
<v>.y</v>
<v>.y</v>
<v>.y</v>
<v>.y</v>
<v>.y</v>
</o>
<o>
<v>.z</v>
<v>.z</v>
<v>.z</v>
<v>.z</v>
<v>.z</v>
</o>
</data>
<value_labels>
</value_labels>
</dta>
